spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/lettering
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none


  flyway:
    baseline-version: 1
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db

